name: C/C++ Compile and Test - CI

on:
  push:
      branches: [ main ]
  pull_request:
      branches: [ main ]

jobs:
  cpp_compile:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up MinGW
        uses: egor-tensin/setup-mingw@v2

      - name: Compile
        run: |
          mkdir obj
          mingw32-make


  lint_code_base:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: lint
        uses: github/super-linter@v4
        env:
          DEFAULT_BRANCH: main
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VALIDATE_ALL_CODEBASE: false
          VALIDATE_CPP: true
          VALIDATE_CLANG_FORMAT: true
